### ISSUE TITLE
back end user service

### ISSUE THREAD

**Issue by Tekalig** [Besufqad-Mesfin/school-portal-server#4]
1. Admin and Staff Registration Microservice
Description:  
Develop a microservice to allow admin users to register new users (students, teachers, and other admins/staff). This service will handle user creation based on role and ensure proper validation.

Requirements:  
- Allow admin or staff to register users with role-specific details:  
  - Students: Name, email, grade/class, guardian contact, and initial password.  
  - Teachers: Name, email, department, subject(s), and initial password.  
  - Admins/Staff: Name, email, role, department, and initial password.  
- Auto-generate passwords if not provided and email them to the user.  
- Store user data in a centralized database.  
- Restrict registration functionality to authorized users (staff and admins).  

Acceptance Criteria:  
- Admins/staff can successfully register new users.  
- Passwords are securely stored after hashing.  
- Role-based validations are enforced during registration.  
- Unauthorized users cannot access this service.

2. User Login Microservice
Description:  
Provide a secure login service for all user roles (admin, staff, teacher, and student).

Requirements:  
- Authenticate users using their email and password.  
- Verify role-based access during authentication.  
- Return JWTs containing user ID and role claims.  

Acceptance Criteria:  
- Users (admin, staff, teacher, and student) can log in with valid credentials.  
- Tokens are issued upon successful login.  
- Login fails with appropriate errors for invalid credentials or inactive accounts.

**Comment by BirukM14** [comment]
please tell me my next task.
